services:
  mysqldb:
    image: mysql
    restart: always # 종료가 되면 자동 재시작
    volumes:
      - mysql-compose-volume:/var/lib/mysql
      # - ./data:/var/lib/mysql
      # 안전하게 하려면 host
    environment:
      - MYSQL_ROOT_PASSWORD=root1234
      - MYSQL_DATABASE=rootdb
    ports:
      - "3307:3306"

volumes:
  mysql-compose-volume: # 볼륨을 하나 만들어 놓고 위에서 볼륨 연결