FROM mysql

ENV MYSQL_USER=tester
ENV MYSQL_PASSWORD=tester1234
ENV MYSQL_ROOT_PASSWORD=root1234
ENV MYSQL_DATABASE=reacttest

CMD [ "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci" ]